# Generated by Django 3.1.1 on 2020-09-08 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=300),
        ),
    ]
